const usersData = [
  {
    id: 0,
    typeOfEvent: "John Doe",
    dateTime: "2018/01/01",
    locationOfEvent: "Guest",
    status: "Pending",
  },
  {
    id: 1,
    typeOfEvent: "Samppa Nori",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Approved",
  },
  {
    id: 2,
    typeOfEvent: "Estavan Lykos",
    dateTime: "2018/02/01",
    locationOfEvent: "Staff",
    status: "Reject",
  },
  {
    id: 3,
    typeOfEvent: "Chetan Mohamed",
    dateTime: "2018/02/01",
    locationOfEvent: "Admin",
    status: "Cancel",
  },
  {
    id: 4,
    typeOfEvent: "Derick Maximinus",
    dateTime: "2018/03/01",
    locationOfEvent: "Member",
    status: "Pending",
  },
  {
    id: 5,
    typeOfEvent: "Friderik Dávid",
    dateTime: "2018/01/21",
    locationOfEvent: "Staff",
    status: "Approved",
  },
  {
    id: 6,
    typeOfEvent: "Yiorgos Avraamu",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Approved",
  },
  {
    id: 7,
    typeOfEvent: "Avram Tarasios",
    dateTime: "2018/02/01",
    locationOfEvent: "Staff",
    status: "Reject",
  },
  {
    id: 8,
    typeOfEvent: "Quintin Ed",
    dateTime: "2018/02/01",
    locationOfEvent: "Admin",
    status: "Cancel",
  },
  {
    id: 9,
    typeOfEvent: "Enéas Kwadwo",
    dateTime: "2018/03/01",
    locationOfEvent: "Member",
    status: "Pending",
  },
  {
    id: 10,
    typeOfEvent: "Agapetus Tadeáš",
    dateTime: "2018/01/21",
    locationOfEvent: "Staff",
    status: "Approved",
  },
  {
    id: 11,
    typeOfEvent: "Carwyn Fachtna",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Approved",
  },
  {
    id: 12,
    typeOfEvent: "Nehemiah Tatius",
    dateTime: "2018/02/01",
    locationOfEvent: "Staff",
    status: "Reject",
  },
  {
    id: 13,
    typeOfEvent: "Ebbe Gemariah",
    dateTime: "2018/02/01",
    locationOfEvent: "Admin",
    status: "Cancel",
  },
  {
    id: 14,
    typeOfEvent: "Eustorgios Amulius",
    dateTime: "2018/03/01",
    locationOfEvent: "Member",
    status: "Pending",
  },
  {
    id: 15,
    typeOfEvent: "Leopold Gáspár",
    dateTime: "2018/01/21",
    locationOfEvent: "Staff",
    status: "Approved",
  },
  {
    id: 16,
    typeOfEvent: "Pompeius René",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Approved",
  },
  {
    id: 17,
    typeOfEvent: "Paĉjo Jadon",
    dateTime: "2018/02/01",
    locationOfEvent: "Staff",
    status: "Reject",
  },
  {
    id: 18,
    typeOfEvent: "Micheal Mercurius",
    dateTime: "2018/02/01",
    locationOfEvent: "Admin",
    status: "Cancel",
  },
  {
    id: 19,
    typeOfEvent: "Ganesha Dubhghall",
    dateTime: "2018/03/01",
    locationOfEvent: "Member",
    status: "Pending",
  },
  {
    id: 20,
    typeOfEvent: "Hiroto Šimun",
    dateTime: "2018/01/21",
    locationOfEvent: "Staff",
    status: "Approved",
  },
  {
    id: 21,
    typeOfEvent: "Vishnu Serghei",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Approved",
  },
  {
    id: 22,
    typeOfEvent: "Zbyněk Phoibos",
    dateTime: "2018/02/01",
    locationOfEvent: "Staff",
    status: "Reject",
  },
  {
    id: 23,
    typeOfEvent: "Aulus Agmundr",
    dateTime: "2018/01/01",
    locationOfEvent: "Member",
    status: "Pending",
  },
  {
    id: 42,
    typeOfEvent: "Ford Prefect",
    dateTime: "2001/05/25",
    locationOfEvent: "Alien",
    status: "Don't panic!",
  },
];

export default usersData;
